# Numpy 이어서 Reveiw

In [2]:
import numpy as np

# np.lookfor method
- docstring에 keyword search를 하는 함수. 

In [20]:
np.lookfor('shape')

Search results for 'shape'
--------------------------
numpy.shape
    Return the shape of an array.
numpy.reshape
    Gives a new shape to an array without changing its data.
numpy.flip
    Reverse the order of elements in an array along the given axis.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.isin
    Calculates `element in test_elements`, broadcasting over `element` only.
numpy.ones
    Return a new array of given shape and type, filled with ones.
numpy.empty
    Return a new array of given shape and type, without initializing entries.
numpy.zeros
    Return a new array of given shape and type, filled with zeros.
numpy.resize
    Return a new array with the specified shape.
numpy.ndarray
    ndarray(shape, dtype=float, buffer=None, offset=0,
numpy.ndindex
    An N-dimensional iterator object to index arrays.
numpy.squeeze
    Remove single-dimensional entries from the shape of an array.
numpy.ma.shape
    Return the shape of an array.

In [ ]:
np.lookfor('* array')

# Reshape & resize 함수

- reshape method : data를 바꾸지 않으면서 array에 새로운 shape를 주는 함수. 

- resize method : 지정된 shape을 가진 새로운 array를 만드는 함수. 

#### reshape와 resize함수의 차이
- reshape은 data를 바꾸지 않기 때문에 data의 갯수와 새로운 shape의 모양이 일치해야 한다.
- 재할당을 해줘야 한다. 
- -1을 사용해서 저절로 shape을 맞출 수 있다. 



- resize는 숫자의 갯수가 맞지 않아도 잘라서 넣는다.
- 할당이 따로 필요없다. 
- -1을 사용할 수 없다. 

### Reshape 함수

In [ ]:
# a를 만든다. 
a = np.array([[1,2,3], [4,5,6]])
print(a)

In [ ]:
# 만약 shape의 숫자가 일치하지 않는다면, error가 난다. 
a.reshape(4,6)

In [ ]:
# reshape을 해도 같은 파일을 참조하기 때문에 원소를 바꾸면 참조한
# 파일도 바뀐다. 
b = a.reshape(3,2)
b[0][0] = 20

In [ ]:
print("a")
print(a)
print("b")
print(b)

In [4]:
# 그래서 copy를 사용을 하면 좋다. 
b = a.reshape(3,2).copy()
b[0][0] = 5
print(a)
print(b)

# 하지만 마이너스를 사용하면 저절로 값이 맞춰진다.
# 관례상 -1을 사용한다. 
print("\n\n -1 사용")
b = a.reshape(-1,2)
print(b)

NameError: name 'a' is not defined

### resize 함수

In [5]:
# resize함수는 재할당이 필요없다. 
# shape이 맞지 않아도 가능하다. 
a = np.arange(27)
a.resize(3,5)
print(a,"\n")
a.resize(7,9)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]


In [6]:
# 하지만, negative값은 받지 않는다. 
a.resize((-1, 10))

ValueError: negative dimensions not allowed

# Split

#### 함수설명
- array를 여러 sub-array로 나눈다. 
- indices_or_sections은 1-D array로 axis이다. 그래서, split은 axis를 기준으로 잘린다. 

#### 기타 split 함수
hsplit : array를 horizontally하게 sub-array로 자른다. 
vsplit : array를 vertically하게 sub-array로 자른다. 

In [7]:
# 필요한 a를 먼저 만든다.
a = np.arange(20)
a.resize(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [8]:
# a를 row-wise로 2번째를 기준으로 3개의 sub-array로 나눈다. 
np.split(a, (1,2))

# a를 나누면, 0번째 row를 가진 array하나, 1번째 row를 가진 array하나,
# 마지막으로 2,3 row를 가진 array하나로 나뉜다. 

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [9]:
# 반으로 나눌수도 있다. 
np.split(a, (2,2))

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([], shape=(0, 5), dtype=int32),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [10]:
# 혹은 마이너스를 사용할 수도 있다.
np.split(a, (-2, 5))

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]), array([], shape=(0, 5), dtype=int32)]

In [11]:
# row말고 column-wise로도 split을 할 수 있다. 
np.split(a, (2,2), axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16]]), array([], shape=(4, 0), dtype=int32), array([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19]])]

#### axis를 사용하지 않고 hsplit과 vsplit을 사용할 수 있다. 

In [12]:
# vsplit
np.vsplit(a, (2,2))

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([], shape=(0, 5), dtype=int32),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [13]:
# hsplit
np.hsplit(a, (2,3))

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16]]), array([[ 2],
        [ 7],
        [12],
        [17]]), array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19]])]

# Stack

#### 함수설명
- 여러 array를 axis에 따라서 붙인다. 
- axis에 따라 붙인다. 
- axis가 0이면 vertically하게 붙인다. 
- axis가 1이면 

#### 기타 함수
- vstack : axis대신 vertically하게 array를 붙인다. 
- hstack : axis를 horizontally하게 array를 붙인다. 
- np.r_ : row끼리 붙인다. 
- np.c_ : column끼리 붙인다. 
- np.s_ : slicing도 지원한다. 

In [14]:
# array를 준비한다. 
a = np.arange(10)
print(a)
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [15]:
# vertically하게 array를 붙인다. 
c = np.stack((a,b), axis=0)
print(c)
c = np.vstack((a,b))
print(c)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [16]:
# horizontally하게 array를 붙인다. 
c = np.stack((a,b), axis=1)
print(c)
c = np.hstack((a,b))
print(c)

[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]
 [7 7]
 [8 8]
 [9 9]]
[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


In [17]:
c = np.r_[a,b] #np.stack(axis=1)과 같다. 
print(c)

[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


In [18]:
c = np.c_[a,b] #np.hstack()과 같다. 
print(c)

[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]
 [7 7]
 [8 8]
 [9 9]]


In [19]:
# slcing도 가능하다. 
np.arange(1,10)[np.s_[1:8:2]]

array([2, 4, 6, 8])

# Newaxis

#### 함수 설명
- slicing operation과 함께 쓰여 새로운 axis을 만들고 싶을 때 사용한다. 
- None과 같은 의미이다. 


#### 기타함수
- expand_dims : np.newaxis처럼 axis를 추가한다. 
 * 하지만, 차원을 한 단계씩 밖에 증가시키지 못한다. 
 * np.expand_dims(x, axis=0) 은 x[np.newaxis, :]와 x[np.newaxis]와 같다. 
 * np.expand_dims(x, axis=1)은 x[:, np.newaxis]와 같다. 

- swapaxes : 두개의 axes를 교환한다. 

In [25]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
# 새로운 축을 하나 더 만든다.
# 1차원에서 2차원으로 변형.
# 차원이 하나 증가한 것을 볼 수 있다. 
print(a[np.newaxis])

[[0 1 2 3 4 5 6 7 8 9]]


In [33]:
#2차원으로 바꾸고 3차원으로 변형시켜 보자. 
a.resize(2,5)
print(a[np.newaxis])

[[[0 1 2 3 4]
  [5 6 7 8 9]]]


In [35]:
# ::과 코마를 사용할 수도있다. (좀 더 공부 필요.)
a = np.arange(6)

print(a[:,np.newaxis])
print(a[np.newaxis, :])

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[0 1 2 3 4 5]]


In [37]:
# np.newaxis는 None과 같다. 
print(np.newaxis is None)
print(a[:,None])
print(a[None,:])

True
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[0 1 2 3 4 5]]


In [41]:
# np.expand_dims사용

a = np.arange(6)
print(a[np.newaxis])
print(a[np.newaxis,:])
print(np.expand_dims(a, 0))

print("\n")
print(a[:, np.newaxis])
print(np.expand_dims(a,1))

[[0 1 2 3 4 5]]
[[0 1 2 3 4 5]]
[[0 1 2 3 4 5]]


[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [55]:
# swapaxes사용하기 : 두 개의 축을 서로 교환한다. 
a = np.arange(8)
a.resize(2,4)
print(a)
print(np.swapaxes(a, 0, 1))

[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


# Structured array

#### structured array란
- structured array란 datatype이 여러 개의 작은 datatype으로 이루어진 ndarray이다. 
- numpy에서는 structured array를 사용해서 data field를 만들 수 있다. 
- DB의 tuple처럼 사용이 가능하다. 

#### namedtuple란
- python에서 namedtuple이라는 dictionaries형태의 container를 지원한다.
- metaclass처럼 class를 정의하지 않아도 사용이 가능하다. 

#### namedtuple & structured array
- 둘다 비슷한 기능을 가지고 있다. 
- DB에서 tuple, row처럼 빠르게 사용하기 위해 사용된다. 
- disk에 올리지 않고 memory에 올리기 때문에 엄청 access가 빠르다. 

In [59]:
# structured array만드는 법.
# np. array를 사용한다. dtype에 원하는 데이터 타입과 key를 입력한다. 

x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.9)], \
             dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [60]:
print(x)

[('Rex', 9, 81. ) ('Fido', 3, 27.9)]


In [61]:
# array처럼 접근이 가능하다. 
print(x[0])
print(x[1])
print(x[0][0])
print(x[0][1])

('Rex', 9, 81.)
('Fido', 3, 27.9)
Rex
9


In [69]:
# key방식으로 접근이 가능하다. 
x['name']

array(['Rex', 'Fido'], dtype='<U10')

In [71]:
# 하지만, attribute방식으로는 접근이 안된다. 
x.name

AttributeError: 'numpy.ndarray' object has no attribute 'name'

In [62]:
# namedtuple 사용하는 법.
# 먼저, namedtuple을 import한다. 

from collections import namedtuple

In [63]:
Address = namedtuple("Address", ('name', 'age', 'weight'))

In [64]:
a1 = Address('Rex', 10, 25)

In [1]:
# a1을 dir해서 보면 name, age, weight이 있는 것을 볼 수 있다. 
dir(a1)

NameError: name 'a1' is not defined

In [73]:
# attribute방식으로는 접근이 가능하다. 
a1.name

'Rex'

In [2]:
# keyword방식으로는 접근이 안된다. 
a1['name']

NameError: name 'a1' is not defined